Create build for packer box
bloomberg/chef-bcpc pull request #1776
Opened 2021-02-01 15:43 UTC by jingqgeng

Added makefile and updated readme.

2021-02-09 20:33 UTC, jingqgeng reviewed
Talked with David and Justin offline about the PR. Besides the inline comments, there're other revisions we'd like to have on this PR. Including:
- Move /packer under /virtual. 
- Move the build targets in /packer/Makefile to chef-bcpc/Makefile so we don't have a Makefile under /packer (since no other sub-component under /virtual has its own Makefile).
- By default create-packer-box should always override the current box. So the user doesn't have to always call destroy-packer-box before building another box image.
- Since in Vagrantfiles we assume there is a packer box, in the make process we should check if the packer box exists. If not, print out a message explicitly about how the user should build a packer box first. 
- The document (README) can cover a bit more about how the packer make target works and be more explicit about the steps required for a build.
- Update .gitignore so files and binaries generated by packer won't show up in git diff 
- Download and install packer should be part of README. Instead of installing it in the root directory, /usr/local/bin would be a better option. 
- The output box can be better named. For example, bcc-\<os\>-\<version\>, like bcc-ubuntu-18.04.
- Config.json for packer can be parameterized, especially with the base box image (ubuntu-18.04), since it appears both in config.json and in create-packer-box.sh.
- Potentially config.json can be used just as an example like topology.example.yaml under /virtual/topology.

2021-02-25 14:28 UTC, justinjpacheco commented on virtual/packer/packer_box_provision.sh
> +function cleanup_unused_kernel {
the command being run is generic to all unused packages, so perhaps this function should be renamed to `cleanup_unused_packages`?

2021-02-25 14:34 UTC, justinjpacheco commented on virtual/Vagrantfile
> +
could we put this block into a function that is sourced from a shared lib? identical copies are being used in multiple locations

2021-02-25 14:36 UTC, justinjpacheco commented on virtual/Vagrantfile
> +base_box_dir = "~/.vagrant.d/boxes/#{base_box}/0"
i don't think we should assume where the boxes are being stored. `vagrant box list` has the list of every box loaded into vagrants image store which abstracts the box's actual location. Perhaps the `Vagrant` class has access to this information but at the very least you should be able to get this by shelling out to `vagrant box list`

2021-03-01 20:59 UTC, jingqgeng commented on virtual/Vagrantfile
> +base_box_dir = "~/.vagrant.d/boxes/#{base_box}/0"
Didn't find an attribute/function in Vagrant class to check all the boxes added. Used `vagrant box list` instead.

2021-03-01 22:59 UTC, comay commented on README.md
> +'null' are required). An exmaple can be found at [variables.json.example](virtual/packer/
s/exmaple/example/

2021-03-01 22:59 UTC, comay commented on README.md
> +variables.json.example). This step issential for building a packer box as a base image
s/issential/is essential/

2021-03-01 22:59 UTC, comay commented on virtual/Vagrantfile.libvirt
> +require 'json'
Remember to update the copyright year above to 2021.

2021-03-01 22:59 UTC, comay commented on virtual/bin/create-virtual-environment.sh
Remember to update the copyright year above to 2021.

2021-03-01 22:59 UTC, comay commented on virtual/packer/config.json
> +            "type": "shell",
Indentation level incorrect?

2021-03-01 22:59 UTC, comay commented on virtual/packer/packer_box_provision.sh
> +function upgrade_system {
Could the comment from `finish.sh` be added before this function again?

2021-03-01 22:59 UTC, comay commented on virtual/packer/variables.json
> +    "bcc_apt_key_url":"",
Could a space be added after each of the colons for readability?

2021-03-01 22:59 UTC, comay commented on virtual/packer/variables.json.example
> +{
Could a space be added after each of the colons (where missing) for readability?

2021-03-01 22:59 UTC, comay commented on virtual/packer/packer_box_provision.sh
> +#!/usr/bin/env bash
This file should have the same copyright and license block as `finish.sh` did.

2021-03-01 22:59 UTC, comay commented on virtual/packer/packer_box_provision.sh
> +    cleanup_apt_cache
Question for both you & @justinjpacheco - does it make sense to perform this here or later in the function sequence. I'm wondering if it makes sense to have the following order (important thing is downloading the packages to be installed later comes last)

    configure_vagrant_user
    configure_apt
    upgrade_system
    configure_linux_kernel
    cleanup_unused_packages
    cleanup_apt_cache
    download_debs

2021-03-02 00:50 UTC, justinjpacheco commented on virtual/Vagrantfile
> +require 'json'
i think this can be moved into lib/util now

2021-03-02 00:54 UTC, justinjpacheco commented on virtual/packer/packer_box_provision.sh
> +function configure_vagrant_user {
i think this function can be kept in the finish.sh script use by vagrant directly

2021-03-02 16:25 UTC, justinjpacheco commented on virtual/packer/packer_box_provision.sh
> +function configure_vagrant_user {
they will. this function adds the vagrant user to the operations group

2021-03-11 03:02 UTC, comay commented on virtual/lib/util.rb
> +require 'json'
If this file is changed, then the copyright year above should be adjusted too.

2021-03-11 03:02 UTC, comay commented on virtual/network/Vagrantfile
> +base_box = Util.get_base_box_name()
Another file in need of a copyright year update.

2021-03-11 03:02 UTC, comay commented on virtual/network/Vagrantfile.libvirt
> +base_box = Util.get_base_box_name()
Another file in need of a copyright year update.

2021-03-11 18:08 UTC, comay commented on virtual/packer/variables.json
> +{
Given the confusion from this morning, it seems best to not deliver this file but instead 1) document that the appropriate example file be copied into place and edited as needed and 2) the pathname `virtual/packer/variables.json` be added to `.gitignore`.

2021-03-17 21:39 UTC, jingqgeng commented on virtual/lib/util.rb
> +    config_variable_file = File.read(virtual_dir + '/packer/variables.json')
Do you mean the name of the base box we use, or the name of `variables.json`?

2021-03-17 21:48 UTC, jingqgeng commented on virtual/packer/config.json
> +			    "BCC_KERNEL_VERSION={{user `kernel_version`}}"],
I'd prefer not to look for env vars outside of the Packer context. Although the env vars are used a lot in bve, this is the upstream project and the README doesn't mention anywhere about specifying env vars. So maybe we should apply that assumption here. 

For  `http_proxy` and `https_proxy`, I'd rather leave them out for now. They're not used in the packer box. If anyone needs proxy settings, this config file already provides an example of how it can be done.

2021-03-18 14:13 UTC, comay commented on virtual/packer/packer_box_provision.sh
> +    sync;sync;sync;
Only a single sync should be required. :-)

2021-03-18 14:13 UTC, comay commented on virtual/packer/config.json
> +			    "BCC_KERNEL_VERSION={{user `kernel_version`}}"],
Let's discuss this one off-line.

2021-03-18 14:15 UTC, comay commented on virtual/lib/util.rb
> +    config_variable_file = File.read(virtual_dir + '/packer/variables.json')
Let's discuss this one off-line.

2021-03-18 14:54 UTC, tj90241 commented on README.md
> +for the Packer box, upon which we would run provisions. Last but not least, the variable
slightly awkward phrasing here:
"upon which we would run provisions"

"upon which we make further modifications", perhaps?

2021-03-18 14:54 UTC, tj90241 commented on README.md
> +for the Packer box, upon which we would run provisions. Last but not least, the variable
(also, great job updating the docs)

2021-03-18 14:58 UTC, tj90241 commented on virtual/lib/util.rb
> +    config_variable_file = File.read(virtual_dir + '/packer/variables.json')
If we do use `variables.json`, I would love to see support for a `variables.json.overrides`, with the latter being added to `.gitignore` for the project.  With as many customizations as we have, it's easy to stub your toe when checking out different branches if these files are managed by git (and I actually did so while testing this PR - with this file!)

2021-03-18 15:04 UTC, tj90241 commented on virtual/packer/packer_box_provision.sh
> +    # Disable IPv6
Seems like this should be done conditionally based on:
https://github.com/bloomberg/chef-bcpc/blob/188460c93765ef944e1359d43baf5e588b30fbba/ansible/playbooks/roles/common/defaults/main/base.yml#L290

2021-03-18 15:06 UTC, tj90241 commented on virtual/packer/packer_box_provision.sh
> +    # Disable IPv6
(though this kind of opens a can of worms; referencing that from this code isn't nice either... but given that the project's defaults are to enable IPv6, we also cannot disable IPv6 as part of the default provisioning steps here).

2021-03-18 15:11 UTC, tj90241 requested changes
some nits

2021-03-18 15:17 UTC, tj90241 commented on virtual/packer/packer_box_provision.sh
> +    # Disable IPv6
Sorry, misread this as IPv6 is _enabled_ by default, which is not true.  So this is fine as-is.

2021-03-18 17:09 UTC, jingqgeng commented on virtual/lib/util.rb
> +    config_variable_file = File.read(virtual_dir + '/packer/variables.json')
I actually removed `variables.json` out of the commit completely and expected people to follow the instructions in README and create `variables.json` with the right example json file for each provider. 

I think this might work better, since it forces people to think about which provider they use and which example file they should follow, while having `variables.overrides.json` and a default `variables.json` may give an impression to people that they may not need to change any of them.

2021-03-18 17:22 UTC, tj90241 commented on virtual/lib/util.rb
> +    config_variable_file = File.read(virtual_dir + '/packer/variables.json')
@jingqgeng ah okay, that solution works for me!

2021-03-18 20:46 UTC, tj90241 approved these changes

2021-03-18 21:38 UTC, comay reviewed
Looking very good - just three remaining comments below.

2021-03-18 21:38 UTC, comay commented on virtual/bin/create-virtual-environment.sh
> +# Copyright 2021, Bloomberg Finance L.P.
Lines 68-75 which cause the VMs to be rebooted should be removed as we're already running the new kernel.

2021-03-18 21:38 UTC, comay commented on virtual/vagrantbox.json
> +  "vagrant_box": "",
I think we can fill these in with the default name & version (0) of the box as specified in `variables.json` so that it's one less file one needs to edit by default.

2021-03-19 13:44 UTC, jingqgeng commented on virtual/bin/create-virtual-environment.sh
> +# Copyright 2021, Bloomberg Finance L.P.
Good catch! I think this got pulled in when I rebased the branch.

2021-03-19 13:46 UTC, jingqgeng commented on virtual/vagrantbox.json
> +  "vagrant_box": "",
Sure. I'll fill in the variables with the default `output_packer_box_name`  `bcc-ubuntu-18.04`, which is the same for both libvirt and vbox in variables.json

2021-03-19 15:50 UTC, comay submitted a review, later dismissed

2021-03-19 16:04 UTC, jingqgeng commented
Thank you! Will first talk to Mike and let him know about this change and then merge. Otherwise this may break Jenkins.

2021-03-19 16:59 UTC, comay commented
> Thank you! Will first talk to Mike and let him know about this change and then merge. Otherwise this may break Jenkins.

Yes, it definitely will. Mike should pull this change manually and see about uploading a box to BCS or somewhere in the Jenkins infrastructure. Alternatively, he can include building a box and then using it as part of the pipeline but I think those are two different things to test - box building and cluster building.

2021-03-22 16:23 UTC, comay commented
Jing, I believe the following changes would be useful here as well. The first is to set some of the environment variables that trigger warnings from `apt-get` when run in a non-interactive mode. The second is to do a `apt-get update` before doing the download since the clean up earlier may have removed some PPA data.

2021-03-28 00:23 UTC, jingqgeng commented
> Jing, I believe the following changes would be useful here as well. The first is to set some of the environment variables that trigger warnings from `apt-get` when run in a non-interactive mode. The second is to do a `apt-get update` before doing the download since the clean up earlier may have removed some PPA data.
> 
> ```
> diff --git a/virtual/packer/packer_box_provision.sh b/virtual/packer/packer_box_provision.sh
> index 55db83d2..5f208cbc 100644
> --- a/virtual/packer/packer_box_provision.sh
> +++ b/virtual/packer/packer_box_provision.sh
> @@ -20,6 +20,8 @@
>  set -xue
>  set -o pipefail
> 
> +export DEBIAN_FRONTEND='noninteractive' DEBIAN_PRIORITY='critical'
> +
>  apt_key_url="${BCC_APT_KEY_URL}"
>  apt_url="${BCC_APT_URL}"
>  kernel_version="${BCC_KERNEL_VERSION}"
> @@ -53,7 +55,6 @@ EOF
> 
>  # Taken from Ansible's dist upgrade logic for apt(8)
>  function upgrade_system {
> -    env DEBIAN_FRONTEND='noninteractive' DEBIAN_PRIORITY='critical' \
>          apt-get -y \
>              -o 'Dpkg::Options::=--force-confdef' \
>              -o 'Dpkg::Options::=--force-confold' \
> @@ -101,6 +102,7 @@ function cleanup_image {
>  }
> 
>  function download_debs {
> +    apt-get update
>      apt-get install --download-only -y -t bionic-backports \
>          bird2 init-system-helpers
>      apt-get install --download-only -y chrony tinyproxy unbound
> ```

Thank you for the comment! Updated the PR.

2021-03-29 12:09 UTC, comay commented on virtual/packer/packer_box_provision.sh
> +    env DEBIAN_FRONTEND='noninteractive' DEBIAN_PRIORITY='critical' \
Since we moving setting these environment variables to the head of the script, this line can be removed.

2021-03-29 15:25 UTC, jingqgeng commented on virtual/packer/packer_box_provision.sh
> +    env DEBIAN_FRONTEND='noninteractive' DEBIAN_PRIORITY='critical' \
Updated. Thank you!

2021-03-29 21:29 UTC, comay submitted a review, later dismissed
Great work, Jing. Marking this approved although it's not clear if there are still lint errors that need to be addressed - please check the link in the build report.

2021-03-31 21:28 UTC, comay approved these changes

2021-03-31 22:08 UTC, merged