add availability zone anti-affinity.
bloomberg/chef-bcpc pull request #1788
Opened 2021-03-01 19:53 UTC by npustchi

add availability zone anti affinity scheduler filter

Changes

- Checks for a flag in nova attributes, if set the AZ anti-affinity filter is added.
- add the path and filter name to the nova.conf
- copy and compiles the filter.
- restart the nova-scheduler.

Testing performed
- under test.

Additional context
Add any other context about your contribution here.

2021-03-01 20:19 UTC, comay commented on chef/cookbooks/bcpc/files/default/nova/anti_affinity_availability_zone_filter.py
> +# Copyright 2021, Bloomberg L.P.
Nit but the Bloomberg copyright should appear after the other two.

2021-03-01 20:19 UTC, comay commented on chef/cookbooks/bcpc/recipes/nova-head.rb
> +    notifies :restart, 'service[nova-scheduler]', :immediately
Does the restart of `nova-scheduler` belong here or after you've compiled the filter file (assuming that is still necessary?)

2021-03-01 20:35 UTC, npustchi commented on chef/cookbooks/bcpc/files/default/nova/anti_affinity_availability_zone_filter.py
> +# Copyright 2021, Bloomberg L.P.
will do

2021-03-01 20:36 UTC, npustchi commented on chef/cookbooks/bcpc/recipes/nova-head.rb
> +    notifies :restart, 'service[nova-scheduler]', :immediately
yes this will compile the file and then restart the nova scheduler.

2021-03-01 20:38 UTC, tj90241 commented on chef/cookbooks/bcpc/files/default/nova/anti_affinity_availability_zone_filter.py
> +    # a varibale which is checked for all scheduler filters during a rebuild
s/varibale/variable/

2021-03-01 20:46 UTC, tj90241 commented on chef/cookbooks/bcpc/files/default/nova/anti_affinity_availability_zone_filter.py
> +        for host in hosts_group_members:
is there any concern about how this will impact scheduling database load when the server group is large?  It looks like `availability_zones.get_host_availability_zone` -> `nova.objects.aggregate.get_by_host`, which makes a database call -- so we'd be making N database calls 1 server.  I don't know how big we expect server groups to be, or whether or not this level of DB-querying is impactful at scale... am I being pedantic here?

2021-03-02 18:42 UTC, tj90241 commented on chef/cookbooks/bcpc/files/default/nova/anti_affinity_availability_zone_filter.py
> +        for host in hosts_group_members:
okay, if it's used in other parts of the OpenStack scheduling, it must not be too unexpected then.  Thanks!

2021-03-04 16:41 UTC, comay commented on chef/cookbooks/bcpc/files/default/nova/anti_affinity_availability_zone_filter.py
> +        az_hint = spec_obj.get_scheduler_hint('anti_affinity_policy', False)
Since the hint is no longer a boolean, it seems the second argument should either be None or omitted altogether since the default is None. Then the check on line 46-47 can be simplified to

if self.policy_name != policy or az_hint != 'availability_zone':

2021-03-04 16:41 UTC, comay commented on chef/cookbooks/bcpc/files/default/nova/anti_affinity_availability_zone_filter.py
> +        # where the instance is. That case, AntiAffinityFilter must not return
s/AntiAffinityFilter/AntiAffinityAvailabilityZoneFilter/

2021-03-04 16:57 UTC, justinjpacheco requested changes
pr looks good, could you squash the commits please?

2021-03-04 18:29 UTC, npustchi commented
> pr looks good, could you squash the commits please?

changed it.

2021-03-04 18:30 UTC, npustchi commented
> pr looks good, could you squash the commits please?

fixed the commits.

2021-03-04 18:32 UTC, justinjpacheco approved these changes

2021-03-04 18:50 UTC, merged