Moving haproxy recipe to ansible role.
bloomberg/chef-bcpc pull request #1934
Opened 2021-12-17 22:18 UTC by npustchi

Signed-off-by: npustchi <npustchi@bloomberg.net>

This is an initial code review for moving haproxy.

including recipes from haproxy, keystone, and glance./=

2021-12-28 14:20 UTC, tj90241 commented
As part of adding these in Ansible, you should also remove them in Chef, e.g. this glance configuration for HAProxy:
https://github.com/bloomberg/chef-bcpc/blob/master/chef/cookbooks/bcpc/recipes/glance.rb#L124

2021-12-28 15:44 UTC, tj90241 requested changes
Some suggestions, but definitely need to remove things from Chef as they are ported to Ansible as noted in one comment.

2021-12-28 15:44 UTC, tj90241 commented on Makefile
> +run-configure-haproxy : \
If the target is named `run-configure-haproxy`, then I might suggest changing the names of the targets which it pulls in -- later on, when we move things like `keystone` in its entirety to Ansible, the terminology here will be confusing.

Also, I would suggest using `-f 1` here to step through headnodes one at a time.

2021-12-28 15:44 UTC, tj90241 commented on ansible/playbooks/roles/common/defaults/main/base.yml
> +networking_networks_primary_aggregate_cidr: []
Note that pre-existing overrides will have to be moved from the Chef environment to Ansible overrides...

2021-12-28 15:44 UTC, tj90241 commented on ansible/playbooks/roles/haproxy/defaults/main.yml
> +haproxy_qos_slo_url: null
Ditto about pre-existing Chef environment overrides in this case.

2021-12-28 15:44 UTC, tj90241 commented on ansible/playbooks/roles/haproxy/tasks/add-apt-repo.yml
> +    url: "{{ haproxy_repo_key_url if haproxy_repo_key_url is defined else omit }}"
I don't think this task will work if `haproxy_repo_key_*` is not defined, perhaps just assume it is defined and let Ansible explode if not?

2021-12-28 15:56 UTC, tj90241 commented on ansible/playbooks/roles/haproxy/tasks/add-apt-repo.yml
> +    url: "{{ haproxy_repo_key_url if haproxy_repo_key_url is defined else omit }}"
or, if you really wanted to make it conditional, I think these task items need to be in a block that is guarded by `when: ... is not defined`.

2021-12-28 15:57 UTC, npustchi commented
> Some suggestions, but definitely need to remove things from Chef as they are ported to Ansible as noted in one comment.

yap that would be the last step, after adding all services.

2021-12-28 20:16 UTC, npustchi commented on Makefile
> +run-configure-haproxy : \
why do we need to go one headnode at a time.

2021-12-28 20:20 UTC, npustchi commented on ansible/playbooks/roles/haproxy/tasks/add-apt-repo.yml
> +    url: "{{ haproxy_repo_key_url if haproxy_repo_key_url is defined else omit }}"
tested with and without, it works. it should be as we have internal repo and public url repo.

2021-12-28 20:21 UTC, npustchi commented on ansible/playbooks/roles/haproxy/tasks/add-apt-repo.yml
> +    url: "{{ haproxy_repo_key_url if haproxy_repo_key_url is defined else omit }}"
sure, I look into block if it fits this situation.

2021-12-28 20:23 UTC, npustchi commented on ansible/playbooks/roles/common/defaults/main/base.yml
> +networking_networks_primary_aggregate_cidr: []
yes I would create tasks for that.

2021-12-28 20:26 UTC, npustchi commented on ansible/playbooks/roles/haproxy/defaults/main.yml
> +haproxy_qos_slo_url: null
created the task to follow up RDTIBCC-3475

2021-12-30 19:21 UTC, tj90241 commented on Makefile
> +run-configure-haproxy : \
The Makefiles can be used for release deployment; if you deploy to all headnodes at once, you can cause all HAproxy instances to become unavailable simultaneously.  The knock-on effect here is that things like the Consul healthchecks can then fail and the VIP will be withdrawn, etc...

2021-12-30 19:28 UTC, tj90241 commented on ansible/playbooks/roles/haproxy/tasks/add-apt-repo.yml
> +    url: "{{ haproxy_repo_key_url if haproxy_repo_key_url is defined else omit }}"
I removed the definition in defaults.yml for the `haproxy` role, it fails with:
```
TASK [haproxy : import haproxy apt key] ********************************************************************************************************************************************************************************************
fatal: [r1n1]: FAILED! => {}

MSG:

The task includes an option with an undefined variable. The error was: 'haproxy_repo_key_data' is undefined

The error appears to be in '<BUILD_PATH>/modules/chef-bcpc/ansible/playbooks/roles/haproxy/tasks/add-apt-repo.yml': line 1, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
```

with the diff being:
```
--- a/ansible/playbooks/roles/haproxy/defaults/main.yml
+++ b/ansible/playbooks/roles/haproxy/defaults/main.yml
@@ -6,8 +6,8 @@ haproxy_creds: "{{ chef_databags | selectattr('id', 'equalto', 'config') | map(a
 
 # Installation-related configuration options
 haproxy_repo_enabled: true
-haproxy_repo_public_url: ppa:vbernat/haproxy-1.8
-haproxy_repo_key_data: files/haproxy.key
+#haproxy_repo_public_url: ppa:vbernat/haproxy-1.8
+#haproxy_repo_key_data: files/haproxy.key
 haproxy_dependencies:
```

2022-01-14 19:41 UTC, npustchi commented on ansible/playbooks/roles/haproxy/tasks/add-apt-repo.yml
> +    url: "{{ haproxy_repo_key_url if haproxy_repo_key_url is defined else omit }}"
it should not be removed from main.yml, add-apt-repo task is designed to work with chef-bcpc-prop to use internal haproxy repo and without to use public repo. So for testing, I would recommend to remove it from chef-bcpc-prop overrides.yml and build again. Just note that if you already built the env, then you must remove the internal url from apt repo.

2022-01-14 20:21 UTC, tj90241 commented on Makefile
> +run-configure-haproxy : \
Understood, I have some similar enhancements that we did not do because of this.

2022-01-14 20:23 UTC, tj90241 commented on ansible/playbooks/roles/haproxy/tasks/add-apt-repo.yml
> +    url: "{{ haproxy_repo_key_url if haproxy_repo_key_url is defined else omit }}"
I understand that it should not be removed - that's why I'm suggesting that you can change:
```
haproxy_repo_key_url if haproxy_repo_key_url is defined else omit
```

into:
```
haproxy_repo_key_url
```

It is included as a base attribute - it will always be defined. In the event it is undefined (which it should never be), the playbook fails anyways as I demonstrated above.

2022-01-14 20:41 UTC, npustchi commented on ansible/playbooks/roles/haproxy/tasks/add-apt-repo.yml
> +    url: "{{ haproxy_repo_key_url if haproxy_repo_key_url is defined else omit }}"
so the way we get the public repo is using the key in the repo which data should be filled and the internal repo should be used with url. basically the omit serves to use this task with these options, in each case the other parameter, "data" or "url is omitted.

2022-01-14 21:14 UTC, npustchi commented on Makefile
> +run-configure-haproxy : \
will apply -f 1

2022-01-18 15:59 UTC, tj90241 commented on ansible/playbooks/roles/haproxy/filter_plugins/utils.py
> +"""
My Ansible-fu isn't up to snuff: Is it possible to move this `filter_plugin` to a more applicable role?  `get_hosts_chef_role` is something that other things will use in the future and it seems weird to have it in here.

2022-01-18 16:08 UTC, tj90241 commented on Makefile
> +run-configure-haproxy : \
Just reviewing again now and I don't see this yet?

2022-01-19 19:09 UTC, npustchi commented on Makefile
> +configure-keystone-haproxy :
these roles will have the entire recipes for each service, but they only configure haproxy now. I added these tags to represent the current status. When it represents the whole service we can change it to what suits in the future.

2022-01-19 19:24 UTC, npustchi commented on ansible/playbooks/roles/haproxy/filter_plugins/utils.py
> +"""
it is, but if we need to we can use role hierarchy.

2022-01-19 20:53 UTC, npustchi commented on ansible/playbooks/roles/haproxy/filter_plugins/utils.py
> +"""
I actually searched this at the time of design and see role hierarchy is used in such cases.

2022-01-20 19:33 UTC, npustchi commented
> Some suggestions, but definitely need to remove things from Chef as they are ported to Ansible as noted in one comment.

this has been addressed.

2022-01-20 21:35 UTC, tj90241 approved these changes
Please just add an item to backfill moving the filter task.

2022-09-26 04:13 UTC, comay commented on ansible/playbooks/roles/haproxy/templates/haproxy.pem.j2
> +{{ chef_databags[1]['ssl']['key'] | b64decode }}{{ chef_databags[1]['ssl']['crt'] | b64decode }}{{ chef_databags[1]['ssl']['intermediate'] | b64decode if chef_databags[1]['ssl']['intermediate'] is no
The ordering doesn't matter but it would be nice to write this out in the same order they were before: crt, intermediate (if defined) and then key.

Also, does this all need to be bunched up in a single line or can there be a return between each one?

2022-09-26 11:50 UTC, tj90241 commented on ansible/playbooks/roles/haproxy/templates/haproxy.pem.j2
> +{{ chef_databags[1]['ssl']['key'] | b64decode }}{{ chef_databags[1]['ssl']['crt'] | b64decode }}{{ chef_databags[1]['ssl']['intermediate'] | b64decode if chef_databags[1]['ssl']['intermediate'] is no
The ordering changed since the code was written, though yes it should be as it appears in Chef now.

2022-09-26 20:29 UTC, npustchi commented on Makefile
> +run-configure-haproxy : \
The list of clients is based on the order it was done by the chef. I am not sure sorting that may introduce a bug.

2022-09-26 20:29 UTC, npustchi commented on Makefile
> +run-configure-haproxy : \
Though I sorted the rest.

2022-09-26 21:16 UTC, npustchi commented on Makefile
> +configure-keystone-haproxy :
we agreed to keep chef ordering.

2022-09-27 14:55 UTC, comay commented on ansible/playbooks/headnodes.yml
> +    - common
I understand you sorted this list and generally I support that but 1) it's inconsistent with all of the other node types and 2) the original intent was to specify the common role and then the `chef-node` type itself which is sort of the base set of roles for all node types. At this point, the other roles can be listed.

2022-09-27 14:55 UTC, comay commented on ansible/playbooks/roles/haproxy/tasks/main.yml
> +
It appears there's trailing white space at the end of the line.

2022-09-27 14:55 UTC, comay commented on ansible/playbooks/roles/haproxy/templates/429.http.j2
> +HTTP/1.0 429 Too Many Requests
Reopening as the file is still not quite correct I think, in particular there are additional newlines but not carriage returns - how was this file created? Did you run

```
git mv \
  chef/cookbooks/bcpc/templates/default/haproxy/429.http.erb \
  ansible/playbooks/roles/haproxy/templates/429.http.j2
```

before making the parameter updates because it's definitely lost the trailing carriage returns. You may need to use `vim` to edit the file as I know it will preserve the trailing carriage returns.

Here's what I have in doing the above - you can see the two trailing carriage returns at the end of the first six lines.

```
> cat ansible/playbooks/roles/haproxy/templates/429.http.j2
HTTP/1.0 429 Too Many Requests
Cache-Control: no-cache
Connection: close
Content-Type: text/html
Retry-After: {{ haproxy_qos_retry_after }}

<html><body><h1>429 Too Many Requests</h1>
You have executed too many requests and have been rate limited. Please see the s
ervice SLO{{ " at " + haproxy_qos_slo_url if haproxy_qos_slo_url is not none }}
for more information.
</body></html>

>
> cat -e -t -v ansible/playbooks/roles/haproxy/templates/429.http.j2
HTTP/1.0 429 Too Many Requests^M^M$
Cache-Control: no-cache^M^M$
Connection: close^M^M$
Content-Type: text/html^M^M$
Retry-After: {{ haproxy_qos_retry_after }}^M^M$
^M^M$
<html><body><h1>429 Too Many Requests</h1>$
You have executed too many requests and have been rate limited. Please see the s
ervice SLO{{ " at " + haproxy_qos_slo_url if haproxy_qos_slo_url is not none }}
for more information.$
</body></html>$
$
>
```

2022-09-27 14:57 UTC, comay commented on ansible/playbooks/roles/haproxy/templates/haproxy.pem.j2
> +{{ chef_databags[1]['ssl']['crt'] | b64decode }}{{ chef_databags[1]['ssl']['key'] | b64decode }}{{ chef_databags[1]['ssl']['intermediate'] | b64decode if chef_databags[1]['ssl']['intermediate'] is no
Apologies, I missed your question on Slack late yesterday. According to https://github.com/bloomberg/chef-bcpc/blob/development/chef/cookbooks/bcpc/recipes/haproxy.rb#L46-L68, the certs are written out in the order of `crt`, then `intermediate` if it's set, and then `key`. Also checking `/etc/haproxy/haproxy.pem` appears to confirm that.

2022-09-27 18:45 UTC, comay approved these changes

2022-09-29 16:26 UTC, merged