README.md: Add additional reqs for libvirt
bloomberg/chef-bcpc pull request #1935
Opened 2021-12-27 17:47 UTC by tj90241

At least with a clean 20.04 install, these packages were
also required to build a packer image and/or spin up a
libvirt box with vagrant.

2021-12-27 17:48 UTC, justinjpacheco approved these changes

2021-12-27 17:48 UTC, justinjpacheco requested changes
master branch?

2021-12-27 17:58 UTC, justinjpacheco submitted a review, later dismissed

2021-12-27 23:20 UTC, jingqgeng submitted a review, later dismissed

2021-12-29 23:04 UTC, mboruta1 approved these changes

2022-01-03 15:42 UTC, comay submitted a review, later dismissed

2022-01-03 16:20 UTC, comay approved these changes

2022-01-03 16:31 UTC, merged