Release 8.3.11
bloomberg/chef-bcpc pull request #2061
Opened 2022-10-31 21:58 UTC by dmitrymarg

David Comay (1):
      Preseve the CA key in the databag (https://github.com/bloomberg/chef-bcpc/commit/75c9f9cd04b25707541419c97e6fa21add3cea38)

Mengyang Zhang (1):
      change markupsafe version to 2.0.1 (https://github.com/bloomberg/chef-bcpc/commit/caa80f3e2b46ffb093891cc93e49d171dfaed2e6)

Tyler Stachecki (9):
      nova: Allow mutation of schedulers (https://github.com/bloomberg/chef-bcpc/commit/1fb4dd573a8ef57f9f05c9a04b87ddf1cd324444)
      Raise `calicoctl` release to v3.22.5 (https://github.com/bloomberg/chef-bcpc/commit/e4ad49d0e6d6bded9c930bccb8dc300a2a788070)
      nova: Retain MTU during live-migration (https://github.com/bloomberg/chef-bcpc/commit/7b5cf4da307b383299cd59b5553e0b2506384032)
      ceph: Default to autoscaler to warn (https://github.com/bloomberg/chef-bcpc/commit/338d1af7f44199247040744e70fb33187b92f67f)
      networking_calico: Do not checksum DHCP packets (https://github.com/bloomberg/chef-bcpc/commit/50dfbb5f540f0d6225e23b8ea7d61b49097e8ff4)
      ansible/common: Add a task for partitioning vols (https://github.com/bloomberg/chef-bcpc/commit/842b591e98df6fa0e682947b9018453578bbe672)
      ansible/common: Add a configure-volumes task (https://github.com/bloomberg/chef-bcpc/commit/9d9c8e9c2cc5dba5f2ad74505c6962b63b371f46)
      ceph: Revert `ceph-mon` migration support (https://github.com/bloomberg/chef-bcpc/commit/0b6408a6210dc79a6976ac055faaa1bd832923a8)
      Restore patch to retain MTU during migration (https://github.com/bloomberg/chef-bcpc/commit/48413b5ebe3848a04b880055860b1ac385b63128)

npustchi (1):
      fix 429 template. (https://github.com/bloomberg/chef-bcpc/commit/605a8c75f2a06b747b92f3a6cdf1561a8ea5eb33)

2022-11-01 12:02 UTC, tj90241 requested changes
Missing this PR:
https://github.com/bloomberg/chef-bcpc/pull/2060

Perhaps your `origin/development` was behind when you created the release branch?

2022-11-01 14:32 UTC, tj90241 approved these changes

2022-11-02 16:51 UTC, comay commented
Nit but just a note that you have Navid's commit listed twice - once for the merge and once for the actual commit. The former should be dropped:

> Navid Pustchi (1): Merge pull request #2058 from bloomberg/fix-haproxy-http ([5bdf01c](https://github.com/bloomberg/chef-bcpc/commit/5bdf01c9234205cfff5a605494dd5aa416d6e5b1))

and the latter should have his full name listed:

> npustchi (1): fix 429 template. ([e1aa8f2](https://github.com/bloomberg/chef-bcpc/commit/e1aa8f2940e09e27d8483ee61d85567ee258e4a7))

2022-11-02 16:51 UTC, comay approved these changes

2022-11-04 15:47 UTC, merged