Adjust patched `ceph-deploy` file to use official upstream change
bloomberg/chef-bcpc pull request #2147
Opened 2023-06-05 19:44 UTC by comay

While looking at the patches we were carrying with an eye towards Yoga, I noticed that the `ceph-deploy` issue had been fixed upstream and also our version of the file incorrectly has an Apache license added to it while the underlying component is actually [MIT licensed](https://github.com/ceph/ceph-deploy/blob/master/LICENSE). This PR is to use the upstream patch for Python 3.8 and to reflect the correct license. And since this is effectively the upstreamed file, I added it to the `flake8` exception list and left it as-is.

2023-06-05 20:36 UTC, tj90241 requested changes
Unless there's a benefit, I do not think we should be changing Ceph components such as this (which are already deprecated). We use the one packaged from Canonical as is... is something with it not working as expected?

2023-06-05 20:57 UTC, comay commented
> Unless there's a benefit, I do not think we should be changing Ceph components such as this (which are already deprecated). We use the one packaged from Canonical as is... is something with it not working as expected?

Correct, we're using the Canonical package with one file patched for Python 3.8 compatibility - I'm just using the official fix from `ceph/ceph-deploy` to the one that Jing came up with. It's a very minor cleanup to align better with the (final) `ceph-deploy` release that on GitHub.

2023-06-05 21:10 UTC, tj90241 commented
Was there anything _functionally_ problematic with the code, though?

Most of the changes within this PR are linting-related -- the irony being that _said changes now made the linter we use upset_ ... and so we have to add an exclusion to our linting configuration that was formerly not present!

I could see the changes isolate to drop the `distro` module maybe... but I don't agree pulling in any changes that work against our linter when the logic itself is not changing (unless I'm mistaken).

2023-06-05 22:19 UTC, comay commented
The logic is slightly different in how it’s accounting for the deprecation in Python 3.8 but otherwise it’s doing the same sort of decision making. And yes, it’s unfortunate to add it to the exception list but I see that as the norm for upstream code that we’re patching. Even if it was flake8-clean, I think adding it to the exception list makes sense since it is upstream code.

This isn’t big win in any way just a desire to align this with the other code we patch (minimally).
On Jun 5, 2023 at 4:36 PM -0400, Tyler Stachecki ***@***.***>, wrote:
> @tj90241 requested changes on this pull request.
> Unless there's a benefit, I do not think we should be changing Ceph components such as this (which are already deprecated). We use the one packaged from Canonical as is... is something with it not working as expected?
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-06-20 15:42 UTC, comay commented
Closing this as I have a different approach in mind.

2023-06-20 15:42 UTC, closed without merging