Fix build failure.
bloomberg/chef-bcpc pull request #2204
Opened 2023-09-19 19:13 UTC by npustchi

*Issue number of the reported bug or feature request: #<number>*

**Describe your changes**
A clear and concise description of the changes you have made.

**Testing performed**
Describe the testing you have performed to ensure that the bug has been addressed, or that the new feature works as planned.

**Additional context**
Add any other context about your contribution here.

2023-09-21 14:45 UTC, tj90241 approved these changes
Short and simple 👍 

Would not merge into development until @psipika force pushes the branch to true up main and development unless you're coordinating with him.

2023-09-21 17:21 UTC, comay approved these changes

2023-09-21 18:03 UTC, psipika requested changes
Please rebase on latest `development`.
Thank you.

2023-09-26 17:23 UTC, tj90241 approved these changes

2023-09-26 17:38 UTC, merged